server:
  port: 10105

spring:
  profiles:
    active: dev
  dubbo:
    application:
      name: provider
    registry:
      adress: zookeeper://120.24.59.107:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.example.springbootdemo.service
  cache:
    type: REDIS
## Redis 配置
## Redis数据库索引（默认为0）
  redis:
 ## 连接超时时间（毫秒）
    timeout: 0
    database: 0
## Redis服务器地址
    host: 120.24.59.107
## Redis服务器连接端口
    port: 6379
## Redis服务器连接密码（默认为空）
    password: ww456
## 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
## 连接池中的最大空闲连接
        max-idle: 8
## 连接池中的最小空闲连接
        min-idle: 0



## Mybatis 配置
#mybatis.typeAliasesPackage=com.example.springbootdemo.domain
#mybatis.mapperLocations=classpath:mapper/*.xml





